import { Property, Customer } from "@/types";

export const mockProperties: Property[] = [
  {
    id: "1",
    title: "마포구 상암동 디지털큐브 아파트",
    address: "서울시 마포구 상암동 1688",
    propertyType: "아파트",
    dealType: "매매",
    price: 85000,
    area: 84.5,
    rooms: 3,
    bathrooms: 2,
    floor: 12,
    totalFloors: 25,
    description: "상암 DMC 인근 역세권 아파트. 남향, 올수리 완료.",
    images: [],
    isFavorite: true,
    isMyListing: false,
    createdAt: "2024-03-15",
    updatedAt: "2024-03-15",
    contact: "010-1234-5678",
    features: ["역세권", "남향", "올수리"],
  },
  {
    id: "2",
    title: "강남구 역삼동 오피스텔",
    address: "서울시 강남구 역삼동 823-4",
    propertyType: "오피스텔",
    dealType: "월세",
    price: 0,
    deposit: 3000,
    monthlyRent: 120,
    area: 33.2,
    rooms: 1,
    bathrooms: 1,
    floor: 8,
    totalFloors: 15,
    description: "역삼역 도보 3분. 풀옵션 오피스텔.",
    images: [],
    isFavorite: false,
    isMyListing: true,
    createdAt: "2024-03-10",
    updatedAt: "2024-03-12",
    contact: "010-9876-5432",
    features: ["역세권", "풀옵션", "보안"],
  },
  {
    id: "3",
    title: "서초구 서초동 빌라 전세",
    address: "서울시 서초구 서초동 1425",
    propertyType: "빌라",
    dealType: "전세",
    price: 35000,
    area: 59.8,
    rooms: 2,
    bathrooms: 1,
    floor: 3,
    totalFloors: 5,
    description: "교대역 도보 5분. 채광 좋은 빌라.",
    images: [],
    isFavorite: true,
    isMyListing: false,
    createdAt: "2024-03-08",
    updatedAt: "2024-03-08",
    features: ["역세권", "채광좋음"],
  },
  {
    id: "4",
    title: "용산구 이태원동 상가",
    address: "서울시 용산구 이태원동 34-12",
    propertyType: "상가",
    dealType: "월세",
    price: 0,
    deposit: 5000,
    monthlyRent: 250,
    area: 66.0,
    rooms: 1,
    bathrooms: 1,
    floor: 1,
    totalFloors: 4,
    description: "이태원 메인 거리 1층 상가. 유동인구 많음.",
    images: [],
    isFavorite: false,
    isMyListing: true,
    createdAt: "2024-03-05",
    updatedAt: "2024-03-06",
    contact: "010-5555-1234",
    features: ["1층", "유동인구", "코너"],
  },
  {
    id: "5",
    title: "마포구 합정동 원룸",
    address: "서울시 마포구 합정동 412-3",
    propertyType: "원룸",
    dealType: "월세",
    price: 0,
    deposit: 1000,
    monthlyRent: 65,
    area: 19.8,
    rooms: 1,
    bathrooms: 1,
    floor: 4,
    totalFloors: 6,
    description: "합정역 도보 7분. 깨끗한 원룸.",
    images: [],
    isFavorite: false,
    isMyListing: false,
    createdAt: "2024-03-01",
    updatedAt: "2024-03-01",
    features: ["역세권", "풀옵션"],
  },
  {
    id: "6",
    title: "송파구 잠실동 아파트",
    address: "서울시 송파구 잠실동 10",
    propertyType: "아파트",
    dealType: "매매",
    price: 120000,
    area: 112.3,
    rooms: 4,
    bathrooms: 2,
    floor: 18,
    totalFloors: 30,
    description: "잠실 롯데월드타워 인접. 한강뷰 아파트.",
    images: [],
    isFavorite: true,
    isMyListing: false,
    createdAt: "2024-02-28",
    updatedAt: "2024-03-01",
    features: ["한강뷰", "대단지", "주차"],
  },
  {
    id: "7",
    title: "성동구 성수동 오피스텔",
    address: "서울시 성동구 성수동2가 300",
    propertyType: "오피스텔",
    dealType: "전세",
    price: 22000,
    area: 45.5,
    rooms: 1,
    bathrooms: 1,
    floor: 6,
    totalFloors: 20,
    description: "성수역 초역세권. 신축 오피스텔.",
    images: [],
    isFavorite: false,
    isMyListing: false,
    createdAt: "2024-02-25",
    updatedAt: "2024-02-25",
    features: ["신축", "역세권", "풀옵션"],
  },
  {
    id: "8",
    title: "영등포구 여의도동 아파트",
    address: "서울시 영등포구 여의도동 23",
    propertyType: "아파트",
    dealType: "매매",
    price: 180000,
    area: 145.0,
    rooms: 4,
    bathrooms: 2,
    floor: 32,
    totalFloors: 45,
    description: "여의도 한강뷰 프리미엄 아파트.",
    images: [],
    isFavorite: false,
    isMyListing: true,
    createdAt: "2024-02-20",
    updatedAt: "2024-02-22",
    contact: "010-3333-4444",
    features: ["한강뷰", "프리미엄", "주차"],
  },
  {
    id: "9",
    title: "강남구 대치동 래미안 아파트",
    address: "서울시 강남구 대치동 316",
    propertyType: "아파트",
    dealType: "매매",
    price: 245000,
    area: 165.3,
    rooms: 4,
    bathrooms: 2,
    floor: 22,
    totalFloors: 35,
    description: "대치동 학군 최고 입지. 남향 대단지 아파트.",
    images: [],
    isFavorite: true,
    isMyListing: false,
    createdAt: "2024-03-12",
    updatedAt: "2024-03-12",
    contact: "010-2222-3333",
    features: ["남향", "대단지", "학군", "주차"],
  },
  {
    id: "10",
    title: "서초구 반포동 아크로리버파크",
    address: "서울시 서초구 반포동 1-1",
    propertyType: "아파트",
    dealType: "매매",
    price: 230000,
    area: 198.5,
    rooms: 5,
    bathrooms: 3,
    floor: 28,
    totalFloors: 38,
    description: "반포 한강변 프리미엄 아파트. 한강뷰 보장.",
    images: [],
    isFavorite: true,
    isMyListing: false,
    createdAt: "2024-03-01",
    updatedAt: "2024-03-02",
    features: ["한강뷰", "프리미엄", "대단지", "주차"],
  },
  {
    id: "11",
    title: "마포구 연남동 빌라 전세",
    address: "서울시 마포구 연남동 228-5",
    propertyType: "빌라",
    dealType: "전세",
    price: 28000,
    area: 52.4,
    rooms: 2,
    bathrooms: 1,
    floor: 2,
    totalFloors: 4,
    description: "연남동 카페거리 인접. 깔끔한 올수리 빌라.",
    images: [],
    isFavorite: false,
    isMyListing: false,
    createdAt: "2024-02-28",
    updatedAt: "2024-02-28",
    features: ["올수리", "역세권"],
  },
  {
    id: "12",
    title: "용산구 한남동 오피스텔",
    address: "서울시 용산구 한남동 683",
    propertyType: "오피스텔",
    dealType: "월세",
    price: 0,
    deposit: 5000,
    monthlyRent: 150,
    area: 42.8,
    rooms: 1,
    bathrooms: 1,
    floor: 10,
    totalFloors: 22,
    description: "한남동 고급 오피스텔. 풀옵션, 보안 우수.",
    images: [],
    isFavorite: false,
    isMyListing: true,
    createdAt: "2024-03-05",
    updatedAt: "2024-03-06",
    contact: "010-4444-5555",
    features: ["풀옵션", "보안", "주차"],
  },
  {
    id: "13",
    title: "송파구 문정동 상가",
    address: "서울시 송파구 문정동 642-3",
    propertyType: "상가",
    dealType: "매매",
    price: 95000,
    area: 78.2,
    rooms: 1,
    bathrooms: 1,
    floor: 1,
    totalFloors: 6,
    description: "문정법조단지 인근 1층 코너 상가. 유동인구 풍부.",
    images: [],
    isFavorite: false,
    isMyListing: false,
    createdAt: "2024-02-15",
    updatedAt: "2024-02-15",
    contact: "010-6666-7777",
    features: ["1층", "유동인구", "코너"],
  },
  {
    id: "14",
    title: "성동구 왕십리동 원룸",
    address: "서울시 성동구 왕십리로 222",
    propertyType: "원룸",
    dealType: "월세",
    price: 0,
    deposit: 500,
    monthlyRent: 50,
    area: 16.5,
    rooms: 1,
    bathrooms: 1,
    floor: 3,
    totalFloors: 5,
    description: "왕십리역 도보 5분. 대학가 인근 깨끗한 원룸.",
    images: [],
    isFavorite: false,
    isMyListing: false,
    createdAt: "2024-01-28",
    updatedAt: "2024-01-28",
    features: ["역세권", "풀옵션"],
  },
  {
    id: "15",
    title: "종로구 평창동 단독주택 토지",
    address: "서울시 종로구 평창동 산1-5",
    propertyType: "토지",
    dealType: "매매",
    price: 185000,
    area: 198.0,
    rooms: 0,
    bathrooms: 0,
    description: "평창동 주택지 토지. 건축 허가 가능. 조용한 환경.",
    images: [],
    isFavorite: false,
    isMyListing: false,
    createdAt: "2024-01-20",
    updatedAt: "2024-01-20",
    features: ["남향", "채광좋음"],
  },
  {
    id: "16",
    title: "중구 충무로 오피스텔",
    address: "서울시 중구 충무로3가 24-1",
    propertyType: "오피스텔",
    dealType: "전세",
    price: 25000,
    area: 39.7,
    rooms: 1,
    bathrooms: 1,
    floor: 9,
    totalFloors: 18,
    description: "충무로역 초역세권 신축 오피스텔. 보안 철저.",
    images: [],
    isFavorite: false,
    isMyListing: false,
    createdAt: "2024-02-10",
    updatedAt: "2024-02-10",
    features: ["역세권", "신축", "보안"],
  },
  {
    id: "17",
    title: "강서구 마곡동 아파트",
    address: "서울시 강서구 마곡동 757",
    propertyType: "아파트",
    dealType: "매매",
    price: 78000,
    area: 84.9,
    rooms: 3,
    bathrooms: 2,
    floor: 15,
    totalFloors: 28,
    description: "마곡지구 신축 대단지 아파트. 마곡나루역 인접.",
    images: [],
    isFavorite: false,
    isMyListing: true,
    createdAt: "2024-03-08",
    updatedAt: "2024-03-09",
    contact: "010-8888-9999",
    features: ["신축", "대단지", "역세권", "주차"],
  },
  {
    id: "18",
    title: "관악구 봉천동 원룸",
    address: "서울시 관악구 봉천동 1695-3",
    propertyType: "원룸",
    dealType: "월세",
    price: 0,
    deposit: 1000,
    monthlyRent: 45,
    area: 18.2,
    rooms: 1,
    bathrooms: 1,
    floor: 5,
    totalFloors: 7,
    description: "서울대입구역 도보 8분. 풀옵션 원룸.",
    images: [],
    isFavorite: false,
    isMyListing: false,
    createdAt: "2024-01-15",
    updatedAt: "2024-01-15",
    features: ["역세권", "풀옵션"],
  },
  {
    id: "19",
    title: "동작구 흑석동 빌라",
    address: "서울시 동작구 흑석동 221-8",
    propertyType: "빌라",
    dealType: "전세",
    price: 22000,
    area: 49.6,
    rooms: 2,
    bathrooms: 1,
    floor: 3,
    totalFloors: 4,
    description: "흑석역 도보 3분. 중앙대 인근 조용한 빌라.",
    images: [],
    isFavorite: false,
    isMyListing: false,
    createdAt: "2024-02-05",
    updatedAt: "2024-02-05",
    features: ["역세권", "채광좋음"],
  },
  {
    id: "20",
    title: "강남구 신사동 상가",
    address: "서울시 강남구 신사동 550-12",
    propertyType: "상가",
    dealType: "월세",
    price: 0,
    deposit: 10000,
    monthlyRent: 300,
    area: 89.3,
    rooms: 1,
    bathrooms: 1,
    floor: 1,
    totalFloors: 5,
    description: "가로수길 메인 도로변 1층 상가. 프리미엄 입지.",
    images: [],
    isFavorite: true,
    isMyListing: false,
    createdAt: "2024-03-14",
    updatedAt: "2024-03-14",
    contact: "010-1111-8888",
    features: ["1층", "유동인구", "프리미엄", "코너"],
  },
  {
    id: "21",
    title: "송파구 가락동 아파트",
    address: "서울시 송파구 가락동 178",
    propertyType: "아파트",
    dealType: "전세",
    price: 62000,
    area: 99.2,
    rooms: 3,
    bathrooms: 2,
    floor: 7,
    totalFloors: 18,
    description: "가락시장역 인접. 올수리 완료된 깨끗한 아파트.",
    images: [],
    isFavorite: false,
    isMyListing: false,
    createdAt: "2024-02-20",
    updatedAt: "2024-02-21",
    features: ["역세권", "올수리", "대단지"],
  },
  {
    id: "22",
    title: "마포구 서교동 복층 오피스텔",
    address: "서울시 마포구 서교동 395-2",
    propertyType: "오피스텔",
    dealType: "월세",
    price: 0,
    deposit: 3000,
    monthlyRent: 100,
    area: 45.0,
    rooms: 1,
    bathrooms: 1,
    floor: 5,
    totalFloors: 8,
    description: "홍대입구역 도보 5분. 복층 구조 오피스텔.",
    images: [],
    isFavorite: false,
    isMyListing: false,
    createdAt: "2024-02-12",
    updatedAt: "2024-02-12",
    features: ["역세권", "복층", "풀옵션"],
  },
  {
    id: "23",
    title: "영등포구 당산동 아파트",
    address: "서울시 영등포구 당산동 121-5",
    propertyType: "아파트",
    dealType: "매매",
    price: 67000,
    area: 72.8,
    rooms: 3,
    bathrooms: 1,
    floor: 10,
    totalFloors: 20,
    description: "당산역 역세권 아파트. 영등포 생활권 편리.",
    images: [],
    isFavorite: false,
    isMyListing: true,
    createdAt: "2024-01-25",
    updatedAt: "2024-01-26",
    contact: "010-7777-2222",
    features: ["역세권", "주차"],
  },
  {
    id: "24",
    title: "서초구 방배동 빌라",
    address: "서울시 서초구 방배동 847-3",
    propertyType: "빌라",
    dealType: "월세",
    price: 0,
    deposit: 2000,
    monthlyRent: 80,
    area: 43.1,
    rooms: 2,
    bathrooms: 1,
    floor: 2,
    totalFloors: 4,
    description: "방배역 도보 7분. 조용한 주택가 빌라.",
    images: [],
    isFavorite: false,
    isMyListing: false,
    createdAt: "2024-01-18",
    updatedAt: "2024-01-18",
    features: ["남향", "채광좋음"],
  },
  {
    id: "25",
    title: "성동구 성수동 테라스하우스",
    address: "서울시 성동구 성수동1가 685-700",
    propertyType: "빌라",
    dealType: "매매",
    price: 58000,
    area: 82.6,
    rooms: 3,
    bathrooms: 2,
    floor: 4,
    totalFloors: 4,
    description: "성수동 핫플레이스 인근. 넓은 테라스 보유.",
    images: [],
    isFavorite: true,
    isMyListing: false,
    createdAt: "2024-03-10",
    updatedAt: "2024-03-10",
    features: ["테라스", "신축", "주차"],
  },
  {
    id: "26",
    title: "용산구 이촌동 아파트",
    address: "서울시 용산구 이촌동 301-67",
    propertyType: "아파트",
    dealType: "전세",
    price: 78000,
    area: 135.2,
    rooms: 4,
    bathrooms: 2,
    floor: 20,
    totalFloors: 32,
    description: "이촌 한강변 아파트. 한강뷰와 남향 동시 확보.",
    images: [],
    isFavorite: false,
    isMyListing: false,
    createdAt: "2024-02-18",
    updatedAt: "2024-02-19",
    features: ["한강뷰", "남향", "대단지"],
  },
  {
    id: "27",
    title: "종로구 부암동 토지",
    address: "서울시 종로구 부암동 245",
    propertyType: "토지",
    dealType: "매매",
    price: 120000,
    area: 165.0,
    rooms: 0,
    bathrooms: 0,
    description: "북악산 자락 토지. 전원주택 부지로 적합.",
    images: [],
    isFavorite: false,
    isMyListing: false,
    createdAt: "2024-01-10",
    updatedAt: "2024-01-10",
    features: ["남향", "채광좋음"],
  },
  {
    id: "28",
    title: "강남구 청담동 오피스텔",
    address: "서울시 강남구 청담동 118-17",
    propertyType: "오피스텔",
    dealType: "매매",
    price: 75000,
    area: 56.3,
    rooms: 1,
    bathrooms: 1,
    floor: 14,
    totalFloors: 25,
    description: "청담동 프리미엄 오피스텔. 인테리어 올수리 완료.",
    images: [],
    isFavorite: false,
    isMyListing: true,
    createdAt: "2024-02-22",
    updatedAt: "2024-02-23",
    contact: "010-5555-9999",
    features: ["프리미엄", "올수리", "보안", "주차"],
  },
  {
    id: "29",
    title: "관악구 신림동 원룸",
    address: "서울시 관악구 신림동 1432-7",
    propertyType: "원룸",
    dealType: "월세",
    price: 0,
    deposit: 500,
    monthlyRent: 40,
    area: 15.3,
    rooms: 1,
    bathrooms: 1,
    floor: 2,
    totalFloors: 5,
    description: "신림역 도보 4분. 가성비 좋은 원룸.",
    images: [],
    isFavorite: false,
    isMyListing: false,
    createdAt: "2024-01-12",
    updatedAt: "2024-01-12",
    features: ["역세권"],
  },
  {
    id: "30",
    title: "중구 신당동 상가",
    address: "서울시 중구 신당동 340-2",
    propertyType: "상가",
    dealType: "매매",
    price: 45000,
    area: 55.8,
    rooms: 1,
    bathrooms: 1,
    floor: 1,
    totalFloors: 5,
    description: "신당역 인근 1층 상가. 음식점 운영 적합.",
    images: [],
    isFavorite: false,
    isMyListing: false,
    createdAt: "2024-02-08",
    updatedAt: "2024-02-08",
    features: ["1층", "유동인구"],
  },
  {
    id: "31",
    title: "강서구 화곡동 아파트",
    address: "서울시 강서구 화곡동 980-12",
    propertyType: "아파트",
    dealType: "전세",
    price: 35000,
    area: 75.4,
    rooms: 3,
    bathrooms: 1,
    floor: 8,
    totalFloors: 15,
    description: "화곡역 도보 6분. 실속형 전세 아파트.",
    images: [],
    isFavorite: false,
    isMyListing: false,
    createdAt: "2024-01-30",
    updatedAt: "2024-01-30",
    features: ["역세권", "주차"],
  },
  {
    id: "32",
    title: "송파구 방이동 오피스텔",
    address: "서울시 송파구 방이동 44-3",
    propertyType: "오피스텔",
    dealType: "월세",
    price: 0,
    deposit: 2000,
    monthlyRent: 85,
    area: 28.5,
    rooms: 1,
    bathrooms: 1,
    floor: 7,
    totalFloors: 12,
    description: "올림픽공원 인접. 풀옵션 오피스텔.",
    images: [],
    isFavorite: false,
    isMyListing: false,
    createdAt: "2024-03-02",
    updatedAt: "2024-03-02",
    features: ["풀옵션", "보안"],
  },
  {
    id: "33",
    title: "동작구 상도동 아파트",
    address: "서울시 동작구 상도동 299",
    propertyType: "아파트",
    dealType: "매매",
    price: 62000,
    area: 68.7,
    rooms: 2,
    bathrooms: 1,
    floor: 5,
    totalFloors: 12,
    description: "숭실대입구역 인접. 학군 좋은 소형 아파트.",
    images: [],
    isFavorite: false,
    isMyListing: false,
    createdAt: "2024-02-14",
    updatedAt: "2024-02-14",
    features: ["역세권", "학군"],
  },
  {
    id: "34",
    title: "마포구 공덕동 아파트",
    address: "서울시 마포구 공덕동 105-4",
    propertyType: "아파트",
    dealType: "전세",
    price: 55000,
    area: 95.0,
    rooms: 3,
    bathrooms: 2,
    floor: 16,
    totalFloors: 24,
    description: "공덕역 트리플 역세권. 대단지 신축 아파트.",
    images: [],
    isFavorite: true,
    isMyListing: false,
    createdAt: "2024-03-13",
    updatedAt: "2024-03-13",
    features: ["역세권", "신축", "대단지", "주차"],
  },
  {
    id: "35",
    title: "강남구 삼성동 빌라",
    address: "서울시 강남구 삼성동 160-8",
    propertyType: "빌라",
    dealType: "월세",
    price: 0,
    deposit: 3000,
    monthlyRent: 110,
    area: 56.0,
    rooms: 2,
    bathrooms: 1,
    floor: 3,
    totalFloors: 5,
    description: "삼성역 도보 10분. 반려동물 가능한 빌라.",
    images: [],
    isFavorite: false,
    isMyListing: false,
    createdAt: "2024-02-25",
    updatedAt: "2024-02-25",
    features: ["반려동물", "남향"],
  },
  {
    id: "36",
    title: "영등포구 문래동 오피스텔",
    address: "서울시 영등포구 문래동3가 55-16",
    propertyType: "오피스텔",
    dealType: "전세",
    price: 18000,
    area: 33.8,
    rooms: 1,
    bathrooms: 1,
    floor: 11,
    totalFloors: 20,
    description: "문래역 초역세권. 신축 오피스텔, 보안 우수.",
    images: [],
    isFavorite: false,
    isMyListing: false,
    createdAt: "2024-01-22",
    updatedAt: "2024-01-22",
    features: ["역세권", "신축", "보안"],
  },
  {
    id: "37",
    title: "서초구 잠원동 아파트",
    address: "서울시 서초구 잠원동 69-8",
    propertyType: "아파트",
    dealType: "매매",
    price: 155000,
    area: 120.5,
    rooms: 4,
    bathrooms: 2,
    floor: 25,
    totalFloors: 35,
    description: "신반포역 인접. 한강뷰 대형 아파트.",
    images: [],
    isFavorite: false,
    isMyListing: true,
    createdAt: "2024-03-07",
    updatedAt: "2024-03-08",
    contact: "010-2222-6666",
    features: ["한강뷰", "남향", "대단지", "프리미엄"],
  },
  {
    id: "38",
    title: "종로구 삼청동 상가",
    address: "서울시 종로구 삼청동 35-4",
    propertyType: "상가",
    dealType: "월세",
    price: 0,
    deposit: 8000,
    monthlyRent: 200,
    area: 62.5,
    rooms: 1,
    bathrooms: 1,
    floor: 1,
    totalFloors: 3,
    description: "삼청동 관광 상권 1층 상가. 카페/갤러리 운영 적합.",
    images: [],
    isFavorite: true,
    isMyListing: false,
    createdAt: "2024-02-02",
    updatedAt: "2024-02-03",
    contact: "010-3333-1111",
    features: ["1층", "유동인구", "프리미엄"],
  },
];

export const mockCustomers: Customer[] = [
  {
    id: "1",
    name: "김서영",
    phone: "010-1111-2222",
    email: "kim@email.com",
    memo: "마포구 쪽 아파트 관심. 내년 초 입주 희망.",
    interestedIn: ["매매"],
    budget: { min: 60000, max: 90000 },
    preferredArea: "마포구",
    createdAt: "2024-03-10",
  },
  {
    id: "2",
    name: "이준호",
    phone: "010-3333-4444",
    memo: "강남 오피스텔 전세 찾는 중. 직장 근처.",
    interestedIn: ["전세"],
    budget: { min: 20000, max: 30000 },
    preferredArea: "강남구",
    createdAt: "2024-03-08",
  },
  {
    id: "3",
    name: "박미진",
    phone: "010-5555-6666",
    email: "park@email.com",
    memo: "신혼부부. 2룸 이상 빌라/아파트. 서초 선호.",
    interestedIn: ["전세", "매매"],
    budget: { min: 30000, max: 50000 },
    preferredArea: "서초구",
    createdAt: "2024-03-05",
  },
  {
    id: "4",
    name: "정태민",
    phone: "010-7777-8888",
    memo: "상가 투자 목적. 1층 선호. 월세 수익 중요.",
    interestedIn: ["매매", "월세"],
    budget: { min: 50000, max: 100000 },
    createdAt: "2024-03-01",
  },
  {
    id: "5",
    name: "최유나",
    phone: "010-9999-0000",
    email: "choi@email.com",
    memo: "대학생. 합정/홍대 근처 원룸 월세.",
    interestedIn: ["월세"],
    budget: { min: 500, max: 1500 },
    preferredArea: "마포구",
    createdAt: "2024-02-28",
  },
];
